// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckForUpdates() {
  return window['go']['main']['App']['CheckForUpdates']();
}

export function ClearCache() {
  return window['go']['main']['App']['ClearCache']();
}

export function DownloadAndInstallUpdate(arg1) {
  return window['go']['main']['App']['DownloadAndInstallUpdate'](arg1);
}

export function GetAllBenchmarkProgresses() {
  return window['go']['main']['App']['GetAllBenchmarkProgresses']();
}

export function GetBenchmarkProgress(arg1) {
  return window['go']['main']['App']['GetBenchmarkProgress'](arg1);
}

export function GetBenchmarks() {
  return window['go']['main']['App']['GetBenchmarks']();
}

export function GetDefaultSettings() {
  return window['go']['main']['App']['GetDefaultSettings']();
}

export function GetFavoriteBenchmarks() {
  return window['go']['main']['App']['GetFavoriteBenchmarks']();
}

export function GetLastScenarioScores(arg1) {
  return window['go']['main']['App']['GetLastScenarioScores'](arg1);
}

export function GetRecentRuns(arg1) {
  return window['go']['main']['App']['GetRecentRuns'](arg1);
}

export function GetRecordingDirectory() {
  return window['go']['main']['App']['GetRecordingDirectory']();
}

export function GetRecordingStatus() {
  return window['go']['main']['App']['GetRecordingStatus']();
}

export function GetRecordings() {
  return window['go']['main']['App']['GetRecordings']();
}

export function GetRunEvents(arg1) {
  return window['go']['main']['App']['GetRunEvents'](arg1);
}

export function GetRunTrace(arg1) {
  return window['go']['main']['App']['GetRunTrace'](arg1);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function LaunchKovaaksPlaylist(arg1) {
  return window['go']['main']['App']['LaunchKovaaksPlaylist'](arg1);
}

export function LaunchKovaaksScenario(arg1, arg2) {
  return window['go']['main']['App']['LaunchKovaaksScenario'](arg1, arg2);
}

export function QuitApp() {
  return window['go']['main']['App']['QuitApp']();
}

export function RefreshAllBenchmarkProgresses() {
  return window['go']['main']['App']['RefreshAllBenchmarkProgresses']();
}

export function ResetSettings(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ResetSettings'](arg1, arg2, arg3, arg4);
}

export function SaveReplayForLatestRun() {
  return window['go']['main']['App']['SaveReplayForLatestRun']();
}

export function SaveScenarioNote(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveScenarioNote'](arg1, arg2, arg3);
}

export function SaveSessionNote(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveSessionNote'](arg1, arg2, arg3);
}

export function SelectRecordingDirectory() {
  return window['go']['main']['App']['SelectRecordingDirectory']();
}

export function SetAutostart(arg1) {
  return window['go']['main']['App']['SetAutostart'](arg1);
}

export function SetFavoriteBenchmarks(arg1) {
  return window['go']['main']['App']['SetFavoriteBenchmarks'](arg1);
}

export function ShowWindow() {
  return window['go']['main']['App']['ShowWindow']();
}

export function StartWatcher(arg1) {
  return window['go']['main']['App']['StartWatcher'](arg1);
}

export function StopWatcher() {
  return window['go']['main']['App']['StopWatcher']();
}

export function TestRecordingConnection() {
  return window['go']['main']['App']['TestRecordingConnection']();
}

export function UpdateSettings(arg1) {
  return window['go']['main']['App']['UpdateSettings'](arg1);
}
